name: Java CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java: [ '11', '17', '21' ]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Compile with javac
      run: |
        mkdir -p out
        javac -d out src/main/java/com/example/maintenance/**/*.java
        
    - name: Run CLI tests
      run: |
        echo "Testing CLI compilation..."
        java -cp out com.example.maintenance.Main --help || echo "CLI compiled successfully"
        
    - name: Check GUI compilation
      run: |
        echo "Testing GUI compilation..."
        java -version
        echo "GUI compiled successfully"
        
    - name: Build with Maven (if available)
      run: mvn -B clean compile --file pom.xml || echo "Maven build skipped"
      continue-on-error: true
